-- Initial Schema for LabFetch

-- Create pickups table
CREATE TABLE IF NOT EXISTS pickups (
    id SERIAL PRIMARY KEY,
    nombre_mascota VARCHAR(255) NOT NULL,
    tipo_muestra VARCHAR(255) NOT NULL,
    -- Address components
    departamento VARCHAR(100) NOT NULL,
    ciudad VARCHAR(100) NOT NULL,
    tipo_via VARCHAR(50) NOT NULL,
    num_via_p1 VARCHAR(10) NOT NULL,
    letra_via VARCHAR(5) NULL,
    bis BOOLEAN NULL DEFAULT FALSE,
    letra_bis VARCHAR(5) NULL,
    sufijo_cardinal1 VARCHAR(10) NULL,
    num_via2 VARCHAR(10) NOT NULL,
    letra_via2 VARCHAR(5) NULL,
    sufijo_cardinal2 VARCHAR(10) NULL,
    num3 VARCHAR(10) NOT NULL,
    complemento TEXT NULL,
    direccion_completa TEXT NULL, -- Combined address generated by backend/frontend
    latitude NUMERIC(10, 7) NULL, -- For mapping potential
    longitude NUMERIC(10, 7) NULL,
    
    -- Scheduling
    -- fecha_hora_preferida TIMESTAMP WITH TIME ZONE NULL, -- OLD field, removed
    fecha_preferida DATE NULL,                       -- NEW field for preferred date
    turno_preferido VARCHAR(10) NULL,                 -- NEW field for shift ('mañana', 'tarde')

    -- Status and Assignment
    status VARCHAR(50) NOT NULL DEFAULT 'pendiente', -- e.g., pendiente, asignado, recogido, cancelado
    driver_id INTEGER NULL, -- Foreign key to a potential drivers table
    notes TEXT NULL,                          -- NEW field for admin notes
    photo_path VARCHAR(255) NULL,             -- NEW field for path to uploaded photo
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT check_status CHECK (status IN ('pendiente', 'asignado', 'recogido', 'cancelado')),
    CONSTRAINT check_turno_preferido CHECK (turno_preferido IS NULL OR turno_preferido IN ('mañana', 'tarde')) -- Allow NULL or specific values
    -- Add foreign key constraint if/when drivers table exists
    -- CONSTRAINT fk_driver FOREIGN KEY(driver_id) REFERENCES drivers(id)
);

-- ... (Keep the rest of the script: triggers, admin table, settings table, migrations table) ...

-- Trigger to automatically update updated_at on pickup table update
-- ... (Keep existing trigger function and pickup trigger) ...

-- Create admin table (for admin login)
-- ... (Keep existing admin table) ...

-- Create settings table
-- ... (Keep existing settings table and trigger) ...

-- Create migrations table
-- ... (Keep existing migrations table) ...

-- Log completion of this init script in migrations table
INSERT INTO migrations (name) VALUES ('01-schema.sql')
ON CONFLICT (name) DO NOTHING; 