# fly.toml app configuration file generated for labfetch
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "labfetch" # Replace with your actual app name on Fly.io if different
primary_region = "bog"

[build]
  dockerfile = "Dockerfile" # Point to the root Dockerfile

[env]
  # Set non-secret environment variables here
  NODE_ENV = "production"
  PORT = "8080" # Fly.io default, Nginx internally listens on 80, Fly proxy handles mapping
  # DATABASE_URL and JWT_SECRET should be set via 'fly secrets set'

# Define the main process running supervisord
[processes]
  app = "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf" # Default process name is 'app'

# Define the public-facing HTTP service
[http_service]
  internal_port = 80 # Nginx internally listens on 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"] # This service runs the main 'app' process

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/" # Check the root path served by Nginx
    protocol = "http" 